import Joi from 'joi';

export const createEmployeeSchema = Joi.object({
  name: Joi.string().trim().min(2).max(100).required().messages({
    'any.required': 'Employee name is required',
    'string.min': 'Name must be at least 2 characters long',
  }),
  email: Joi.string().email().allow('').trim().lowercase().optional(),
  role: Joi.string().allow('').trim().optional(),
  dept: Joi.string().allow('').trim().optional(),
  loc: Joi.string().allow('').trim().optional(),
  phone: Joi.string().allow('').trim().optional(),
  status: Joi.string().valid('active', 'remote', 'on-leave', 'terminated', 'exited').optional(),
  onboardingStatus: Joi.string().optional(),
  joinDate: Joi.string().allow('').optional(),
  salary: Joi.number().min(0).allow(null).optional(),
  rating: Joi.number().min(0).max(5).allow(null).optional(),
  employmentType: Joi.string().valid('Full-time', 'Part-time', 'Contract', 'Intern').optional(),
  dob: Joi.string().allow('').optional(),
  photo: Joi.string().allow('').optional(),
  managerId: Joi.string().allow(null, '').optional(),
  bankAccount: Joi.string().allow('').optional(),
  ifsc: Joi.string().allow('').optional(),
  gender: Joi.string().allow('').optional(),
  bloodGroup: Joi.string().allow('').optional(),
  personalEmail: Joi.string().allow('').optional(),
  emergencyContact: Joi.object({
    name: Joi.string().allow('').optional(),
    relation: Joi.string().allow('').optional(),
    phone: Joi.string().allow('').optional(),
  }).optional(),
  bankName: Joi.string().allow('').optional(),
  pan: Joi.string().allow('').optional(),
  uan: Joi.string().allow('').optional(),
  esiNumber: Joi.string().allow('').optional(),
  taxRegime: Joi.string().valid('old', 'new').optional(),
  state: Joi.string().allow('').optional(),
  skills: Joi.array().items(Joi.string()).optional(),
  education: Joi.array().items(Joi.object().unknown(true)).optional(),
  experience: Joi.array().items(Joi.object().unknown(true)).optional(),
  family: Joi.array().items(Joi.object().unknown(true)).optional(),
}).unknown(true);

export const patchEmployeeSchema = Joi.object({
  name: Joi.string().trim().min(2).max(100).optional(),
  email: Joi.string().email().allow('').trim().lowercase().optional(),
  role: Joi.string().allow('').trim().optional(),
  dept: Joi.string().allow('').trim().optional(),
  loc: Joi.string().allow('').trim().optional(),
  phone: Joi.string().allow('').trim().optional(),
  status: Joi.string().valid('active', 'remote', 'on-leave', 'terminated', 'exited').optional(),
  onboardingStatus: Joi.string().optional(),
  joinDate: Joi.string().allow('').optional(),
  salary: Joi.number().min(0).allow(null).optional(),
  rating: Joi.number().min(0).max(5).allow(null).optional(),
  employmentType: Joi.string().valid('Full-time', 'Part-time', 'Contract', 'Intern').optional(),
  dob: Joi.string().allow('').optional(),
  photo: Joi.string().allow('').optional(),
  managerId: Joi.string().allow(null, '').optional(),
  bankAccount: Joi.string().allow('').optional(),
  ifsc: Joi.string().allow('').optional(),
  gender: Joi.string().allow('').optional(),
  bloodGroup: Joi.string().allow('').optional(),
  personalEmail: Joi.string().allow('').optional(),
  emergencyContact: Joi.object({
    name: Joi.string().allow('').optional(),
    relation: Joi.string().allow('').optional(),
    phone: Joi.string().allow('').optional(),
  }).optional(),
  bankName: Joi.string().allow('').optional(),
  pan: Joi.string().allow('').optional(),
  uan: Joi.string().allow('').optional(),
  esiNumber: Joi.string().allow('').optional(),
  taxRegime: Joi.string().valid('old', 'new').optional(),
  state: Joi.string().allow('').optional(),
  skills: Joi.array().items(Joi.string()).optional(),
  education: Joi.array().items(Joi.object().unknown(true)).optional(),
  experience: Joi.array().items(Joi.object().unknown(true)).optional(),
  family: Joi.array().items(Joi.object().unknown(true)).optional(),
}).unknown(true);
